apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: hw4
data:
  REDIS_HOST: "redis-service"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: hw4
type: Opaque
stringData:
  REDIS_PASSWORD: "securepassword123" # Not actually used by app.py logic yet, but required by spec
